"""initial migration

Revision ID: b010abc393c1
Revises: f0492877e229
Create Date: 2020-09-24 17:03:52.283738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b010abc393c1'
down_revision = 'f0492877e229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('flavour', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizzas', 'flavour')
    # ### end Alembic commands ###
